credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$pTdjAMeqm.e/KXLMJNe7HOwZfxW7co6A1DeTMiwHOrKgBWYwCTo7m  # Hash para 'fuza123'
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name